site_name: Detran-DF
theme:
  name: 'material'
  logo: 'images/detrandf_logo.png'
  favicon: 'images/detrandf_logo.png'
  language: 'pt'
nav:
  - Início: index.md
  - Planejamento: planejamento.md
  - Pré-Rastreabilidade:
    - Rich Picture: prerastreabilidade/richPicture/richpicture.md
  - Elicitação:
    - Técnicas:
      - Brainstorm: 'elicitação/brainstorm.md'
      - Introspecção: 'elicitação/introspeccao.md'
      - Questionário: 'elicitação/questionario.md'
      - Personas: 'elicitação/persona.md'
    - Resultado: 'elicitação/resultado.md'
    - Priorização: 'elicitação/priorização/moscow.md'
  - Modelagem:
    - Lexico: 'modelagem/lexico.md'
    - Cenários: 'modelagem/cenarios.md'
    - Casos de Uso: 'modelagem/casos.md'
    - Especificação Suplementar: 'modelagem/especificacao.md'
    - Backlog: 'modelagem/backlog.md'
    - NFR Framework: 'modelagem/nfr.md'
  - Apresentações: 'apresentacoes.md'
